### ISSUE TITLE
登陆出现错误

### ISSUE THREAD

**Issue by djwccc** [DP7-Network/HomeEntity#13]
操作系统：ArchLinux
mc启动器：微软官方mc启动器minecraft launcher

期望结果：登陆成功，并不会发生错误
实际发生：进入游戏，实际上没有成功登陆。怎么说呢？登陆后，系统判断登陆失败，但仍然给你进入世界。进入世界之后本该出现在界面顶上的时间条消失。

**Comment by Lama3L9R** [comment]
已在 HomeEntity 1.6.0-1修复
